In [0]:
for new line 
esc + a
or
esc +b

In [0]:
for deleting line
esc +d d

In [0]:
! pip install numpy

In [0]:
3+1

4

# import numpy

In [0]:
import numpy as np #alias

# 1-d array/ vector

In [0]:
#creating array-1d-vector
#1.
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [0]:
#a=np.arange(1,5,0.5)
#a

In [0]:
#2.
b=np.array([1,2,3])
b

array([1, 2, 3])

In [0]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 2-d array-matrix

In [0]:
#2-d array-matrix
#1.
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
#2.
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [0]:
a=np.array([-1,0,1,100])
a

array([ -1,   0,   1, 100])

In [0]:
a=np.array([-1,0,1.0,100])
a

array([ -1.,   0.,   1., 100.])

In [0]:
a=np.array([-1,0,1,100], dtype='int8')
a

array([ -1,   0,   1, 100], dtype=int8)

In [0]:
#shift+tab for getting information about function

In [0]:
a=np.array([-1,0,1,100],dtype='int8')
a*2

array([ -2,   0,   2, -56], dtype=int8)

In [0]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
a[3:7]

array([3, 4, 5, 6])

# 3-d arrays

In [0]:
#3-d arrays
c=np.arange(24).reshape(2,3,4)
c
#2 matrix of 3*4 order is printed

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
#first array
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
#second array
c[1,:,:]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
c[1,1,1]

17

In [0]:
c[0,1,1]

5

# splicing in 2-d array

In [0]:
#splicing in 2-d array
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
a[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [0]:
a[::2,2:]

array([[ 2,  3],
       [10, 11]])

In [0]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [0]:
a[:,-1]

array([ 3,  7, 11])

# Vectorization or broadcasting or maping

In [0]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [0]:
a=np.array([1,2,3])
a*2

array([2, 4, 6])

In [0]:
a**2

array([1, 4, 9], dtype=int32)

In [0]:
a+2

array([3, 4, 5])

In [0]:
#it is vectorization not filtering
a>2

array([False, False,  True])

In [0]:
b=np.array([10,20,30])
b

array([10, 20, 30])

In [0]:
#vectorize multiplication
a*b

array([10, 40, 90])

In [0]:
#vectorize sub
a-b

array([ -9, -18, -27])

In [0]:
#vector are multiplied-it gives scalar result
a.dot(b)

140

In [0]:
#vector is converted into matrix
A=a.reshape(1,3)
A

array([[1, 2, 3]])

In [0]:
B=b.reshape(3,1)
B

array([[10],
       [20],
       [30]])

In [0]:
A.dot(B)

array([[140]])

In [0]:
B.dot(A)
#matrixes are multiplied

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [0]:
a.shape

(3,)

In [0]:
A.shape

(1, 3)

In [0]:
b.shape
#1-d

(3,)

In [0]:
B.shape
#2-d

(3, 1)

# Masking-for filtering in numpy

In [0]:
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
a>15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [0]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
#own data is true because it is creating its own data
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
#own data of "b"is false because it is using data of "a"
b=a.reshape(3,4)
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
c=a[:6]
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [0]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [0]:
c

array([100,   1,   2,   3,   4,   5])

In [0]:
d=a[a>6]
d

array([100,   7,   8,   9,  10,  11])

In [0]:
d=a[a>6]
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
#splicing and replacing uses same data where as masking uses different data
#why numpy is used?

In [0]:
#figure it out of its own means make matrix of 6*2 automatically
a=np.arange(12).reshape(6,-1)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [0]:
#make matrix of 3*4
a=np.arange(12).reshape(-1,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#  convert 2-d matrix into vector

In [0]:
#converting 2-d matrix to vector
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b=a.reshape(-1)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
#also
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# special arrays

In [0]:
np.zeros(4)

array([0., 0., 0., 0.])

In [0]:
#2-d
np.zeros(3,4)

TypeError: data type not understood

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.fives((3,4))
#can't create

AttributeError: module 'numpy' has no attribute 'fives'

In [0]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [0]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
np.linspace(1,5,5)
#(starting ,ending,divide into parts)

array([1., 2., 3., 4., 5.])

In [0]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [0]:
#stastical analysis

In [0]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
np.sum(b)

66

In [0]:
#sum of columns--- rows are merged
np.sum(b,axis=0)

array([12, 15, 18, 21])

In [0]:
#sum of rows
np.sum(b,axis=1)

array([ 6, 22, 38])

In [0]:
np.max(b,axis=1)

array([ 3,  7, 11])

In [0]:
#mean of columns
np.mean(b,axis=0)

array([4., 5., 6., 7.])

In [0]:
#median column wise
np.median(b,axis=0)

array([4., 5., 6., 7.])

In [0]:
np.std(a)

3.452052529534663

In [0]:
np.std(b,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

# time.time()

In [0]:
import time

In [0]:
time.time()#Epoch time (1st jan 1979 midnight)

1560164714.211695

In [0]:
#it is time zone independent number

In [0]:
#generate 3 random numbers
#it generate any number between 0 and 1
#it is based on time.time()
np.random.rand(3)

array([0.09609513, 0.77668376, 0.52004565])

In [0]:
#on execution always gives same output
#seed gives starting point 
np.random.seed(100)
np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

In [0]:
np.random.seed(100)
print(np.random.rand(1))
print(np.random.rand(1))
print(np.random.rand(1))

[0.54340494]
[0.27836939]
[0.42451759]


In [0]:
#range increases from 0 to 100
np.random.rand(1)*100

array([84.47761323])

In [0]:
#range is from 90 to 100
90+np.random.rand(1)*10

array([90.04718856])

In [0]:
#random number generation for normal distribution

In [0]:
#random numbers are generated near mean
mu=100
sigma=15
np.random.normal(mu,sigma,100)

array([105.3201168 ,  88.20903503,  96.52191705, 103.11963521,
       114.03711953, 102.69367468,  91.34257743,  91.99940933,
        96.61896818,  95.27620995, 106.34495177,  93.4175979 ,
        92.47879809,  75.11945745,  84.88634055,  92.36898353,
       111.7223263 ,  90.18428449, 100.61758701,  96.97124639,
        86.93780275, 103.43398105,  93.87940087,  98.44112293,
       123.50768178, 107.45537073, 117.33808502, 127.57917515,
       123.03589927, 103.8249659 ,  87.33764121,  85.25584813,
        95.40853253, 112.57750916,  74.63727759, 117.26760486,
        84.55994729,  92.33511716,  64.59594198, 101.55392698,
       126.08226592, 118.62813767, 101.98619135, 108.66690936,
        76.36141436,  80.60808647,  90.10120317,  86.88992836,
        89.65674085,  91.96780227, 122.91929526, 109.70808685,
        89.83995082,  96.02471807, 111.19159654,  53.03822753,
       100.89432677,  86.87183335, 115.97317493,  91.40271018,
        87.9508227 , 116.39457441, 109.7691637 , 132.40

In [0]:
#mean and standard deviation in every computer is different
mu=100
sigma=15
s=np.random.normal(mu,sigma,100)

In [0]:
np.mean(s)

99.19634924273777

In [0]:
np.std(s)

16.389751926637196

In [0]:
#now mean and SD in every PC is same
np.random.seed(100)
mu=100
sigma=15
s=np.random.normal(mu,sigma,100)

In [0]:
np.mean(s)

98.43751219233904

In [0]:
np.std(s)

14.546287444918226